version: '3.1'

services:
  db:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - 8123:8123
    ulimits:
        nofile:
            soft: 262144
            hard: 262144
    volumes:
      - ./etc/db:/var/lib/clickhouse
